#!/bin/bash
# NEXTFLOW TASK: Map_Tophat2 (2)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /mac/biocore/biocorepipe/tmp/logs/run176/work/cc/a9bcb5fe6f1175512a2574ecda9451/.exitcode
  set +u
  [[ "$COUT" ]] && rm -f "$COUT" || true
  [[ "$CERR" ]] && rm -f "$CERR" || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /mac/biocore/biocorepipe/tmp/logs/run176/work/cc/a9bcb5fe6f1175512a2574ecda9451/.command.begin
[ -f /mac/biocore/biocorepipe/tmp/logs/run176/work/cc/a9bcb5fe6f1175512a2574ecda9451/.command.env ] && source /mac/biocore/biocorepipe/tmp/logs/run176/work/cc/a9bcb5fe6f1175512a2574ecda9451/.command.env
[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
rm -f ggal_1_48850000_49020000.Ggal71.500bpflank.fa
rm -f ggal_gut_1.fq
rm -f ggal_gut_2.fq
rm -f genome.index.1.bt2
rm -f genome.index.2.bt2
rm -f genome.index.3.bt2
rm -f genome.index.4.bt2
rm -f genome.index.rev.1.bt2
rm -f genome.index.rev.2.bt2
ln -s /mac/biocore/nextflowruns/trial1/data/ggal/ggal_1_48850000_49020000.Ggal71.500bpflank.fa ggal_1_48850000_49020000.Ggal71.500bpflank.fa
ln -s /mac/biocore/nextflowruns/trial1/data/ggal/ggal_gut_1.fq ggal_gut_1.fq
ln -s /mac/biocore/nextflowruns/trial1/data/ggal/ggal_gut_2.fq ggal_gut_2.fq
ln -s /mac/biocore/biocorepipe/tmp/logs/run176/work/6e/2c36f74c8fc7fdd597178606a46e3b/genome.index.1.bt2 genome.index.1.bt2
ln -s /mac/biocore/biocorepipe/tmp/logs/run176/work/6e/2c36f74c8fc7fdd597178606a46e3b/genome.index.2.bt2 genome.index.2.bt2
ln -s /mac/biocore/biocorepipe/tmp/logs/run176/work/6e/2c36f74c8fc7fdd597178606a46e3b/genome.index.3.bt2 genome.index.3.bt2
ln -s /mac/biocore/biocorepipe/tmp/logs/run176/work/6e/2c36f74c8fc7fdd597178606a46e3b/genome.index.4.bt2 genome.index.4.bt2
ln -s /mac/biocore/biocorepipe/tmp/logs/run176/work/6e/2c36f74c8fc7fdd597178606a46e3b/genome.index.rev.1.bt2 genome.index.rev.1.bt2
ln -s /mac/biocore/biocorepipe/tmp/logs/run176/work/6e/2c36f74c8fc7fdd597178606a46e3b/genome.index.rev.2.bt2 genome.index.rev.2.bt2


set +e
COUT=$PWD/.command.po; mkfifo "$COUT"
CERR=$PWD/.command.pe; mkfifo "$CERR"
tee .command.out < "$COUT" &
tee1=$!
tee .command.err < "$CERR" >&2 &
tee2=$!
(
/bin/bash /mac/biocore/biocorepipe/tmp/logs/run176/work/cc/a9bcb5fe6f1175512a2574ecda9451/.command.run.1
) >"$COUT" 2>"$CERR" &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
